* Removing Scroll, Tool and Menu bars

It's very easy to set those things. We only need three elisp lines of code on custom-set-variables:


#+BEGIN_SRC emacs-lisp

(custom-set-variables
 '(menu-bar-mode nil)
 '(scroll-bar-mode nil)
 '(tool-bar-mode nil))

#+END_SRC

* Removing Welcoming Screen

#+BEGIN_SRC emacs-lisp

(setq inhibit-startup-screen t)

#+END_SRC

* Opening Always on Fullscreen Mode

There is also a simple command for that. What we are doing is simply adding the specification for the window size to the variable 'default-frame-alist.

#+BEGIN_SRC emacs-lisp

(add-to-list 'default-frame-alist '(fullscreen . maximized))

#+END_SRC

* Adjusting Font Size

#+BEGIN_SRC emacs-lisp

(set-face-attribute 'default nil :height 160)

#+END_SRC

* Starting Server (Daemon Mode)

The emacs Daemon Mode is very useful beacuse you can open files from the terminal that won't open a new instance of emacs. Instead, the file will be shown in your current session of Daemon Emacs.
To open a file from terminal into your daemon emacs session, simply use the command 'emacsclient -n <filename>'. Some users like to make an alias for that command, which is pretty reasonable.

By using the following command on your init file, you get the daemon server started.

#+BEGIN_SRC emacs-lisp

(server-start)

#+END_SRC

* Indentation Configs
  
#+BEGIN_SRC emacs-lisp

(defun my-c-mode-common-hook ()
 ;; my customizations for all of c-mode, c++-mode, objc-mode, java-mode
 (c-set-offset 'substatement-open 0)
 ;; other customizations can go here

 (setq c++-tab-always-indent t)
 (setq c-basic-offset 4)                  ;; Default is 2
 (setq c-indent-level 4)                  ;; Default is 2

 (setq tab-stop-list '(4 8 12 16 20 24 28 32 36 40 44 48 52 56 60))
 (setq tab-width 4)
 (setq indent-tabs-mode t)  ; use spaces only if nil
 )

(add-hook 'c-mode-common-hook 'my-c-mode-common-hook)

#+END_SRC
  
* Package Archives

The first thing to do is to require the emacs package manager and to add org and MELPA package archives:

#+BEGIN_SRC emacs-lisp

(require 'package)

(add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/"))
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
(add-to-list 'package-archives '("melpa-stable" . "http://stable.melpa.org/packages/"))

#+END_SRC

To enable all packages we want, we need to initialize packages and to set the initialization to nil for us to choose which packages we want to be loaded.

#+BEGIN_SRC emacs-lisp

(setq package-enable-at-startup nil)
(package-initialize)

#+END_SRC
* Packages
** let-alist (for older versions)

#+BEGIN_SRC emacs-lisp

(unless (package-installed-p 'let-alist)
  (package-refresh-contents)
  (package-install 'let-alist))

#+END_SRC

** use-package

I decided to use 'use-package' because it is easy to migrate between machines and it is surely easy to install packages and load them.
To install it, we need a simple elisp code:

#+BEGIN_SRC emacs-lisp

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

#+END_SRC

After that, we should require the package and evaluate it:

#+BEGIN_SRC emacs-lisp
(eval-when-compile
  (require 'use-package))
(setq use-package-always-ensure t)

#+END_SRC
  
** helm

#+BEGIN_SRC emacs-lisp

(use-package helm
  :ensure t)

(global-set-key (kbd "M-x") #'helm-M-x)
(global-set-key (kbd "C-x r b") #'helm-filtered-bookmarks)
(global-set-key (kbd "C-x C-f") #'helm-find-files)

(helm-mode 1)

#+END_SRC
   
** projectile

#+BEGIN_SRC emacs-lisp

(use-package projectile
  :ensure t)

#+END_SRC

** C/C++ IDE Packages

   Here are some packages for auto-completion, jump-to-definition, syntax checking, etc. (C/C++)

*** cedet

#+begin_src emacs-lisp

(load-file (concat user-emacs-directory "/cedet/cedet-devel-load.el"))
(load-file (concat user-emacs-directory "cedet/contrib/cedet-contrib-load.el"))

#+end_src

*** helm-gtags

#+begin_src emacs-lisp

(use-package helm-gtags
  :ensure t
  :init
  (setq
    helm-gtags-ignore-case t
    helm-gtags-auto-update t
    helm-gtags-use-input-at-cursor t
    helm-gtags-pulse-at-cursor t
    helm-gtags-prefix-key "\C-cg"
    helm-gtags-suggested-key-mapping t
  )
  :config
    (add-hook 'dired-mode-hook 'helm-gtags-mode)
    (add-hook 'eshell-mode-hook 'helm-gtags-mode)
    (add-hook 'c-mode-hook 'helm-gtags-mode)
    (add-hook 'c++-mode-hook 'helm-gtags-mode)
    (add-hook 'asm-mode-hook 'helm-gtags-mode)

    (define-key helm-gtags-mode-map (kbd "C-c g a") 'helm-gtags-tags-in-this-function)
    (define-key helm-gtags-mode-map (kbd "C-j") 'helm-gtags-select)
    (define-key helm-gtags-mode-map (kbd "M-.") 'helm-gtags-dwim)
    (define-key helm-gtags-mode-map (kbd "M-,") 'helm-gtags-pop-stack)
    (define-key helm-gtags-mode-map (kbd "C-c <") 'helm-gtags-previous-history)
    (define-key helm-gtags-mode-map (kbd "C-c >") 'helm-gtags-next-history)
)

#+end_src

*** function-args

#+begin_src emacs-lisp

(use-package function-args
  :ensure t
  :config (fa-config-default))

#+end_src

*** auto-complete-clang
   
#+begin_src emacs-lisp

(use-package auto-complete-clang
  :ensure t)

#+end_src

*** semantic

#+begin_src emacs-lisp

(require 'cc-mode)
(require 'semantic)

(global-semanticdb-minor-mode 1)
(global-semantic-idle-scheduler-mode 1)

(semantic-mode 1)

#+end_src

*** company

#+begin_src emacs-lisp

(use-package company
  :ensure t
  :init (add-hook 'after-init-hook 'global-company-mode)
  :config
  (setq company-backends (delete 'company-semantic company-backends))
  (define-key c-mode-map  [(tab)] 'company-complete)
  (define-key c++-mode-map  [(tab)] 'company-complete))
  
(use-package company-c-headers
  :ensure t
  :config
  (add-to-list 'company-backends 'company-c-headers)
  (add-to-list 'company-c-headers-path-system "/usr/include/c++/4.2.1/"))

#+end_src

*** yasnippet

#+begin_src emacs-lisp

(use-package yasnippet 
  :ensure t
  :config (yas-global-mode 1))

#+end_src

*** flycheck

#+begin_src emacs-lisp

(use-package flycheck
  :ensure t
  :pin melpa
  :config (global-flycheck-mode))

(use-package flycheck-irony
  :ensure t)

#+end_src

** evil-mode

After installing use-package, we only need to specify the packages we need in a simple way.
We can use the ":ensure" to make sure that the package is going to be installed if it is not available.
I am also using ":init" have evil-mode always active when I open emacs.

#+BEGIN_SRC emacs-lisp

(use-package evil
  :init
  (evil-mode t)
  :ensure t)

(use-package evil-leader
  :ensure t)

#+END_SRC

** powerline

Installing powerline (and poweline-evil) and also configuring it to my selected theme.

#+BEGIN_SRC emacs-lisp

(use-package powerline
  :ensure t)

(use-package powerline-evil
  :ensure t
  :config (powerline-evil-vim-color-theme))

#+END_SRC

** org
   
Installing org is just as simple.

#+BEGIN_SRC emacs-lisp

(use-package org
  :ensure t)

(use-package evil-org
  :ensure t)

#+END_SRC

After that, I want to make some configurations to org. The thing I want is that my agenda commands get all of my TODOS from all org files.

#+BEGIN_SRC emacs-lisp

(defun org-agenda-timeline-all (&optional arg)
  (interactive "P")
  (with-temp-buffer
    (dolist (org-agenda-file org-agenda-files)
      (insert-file-contents org-agenda-file nil)
      (end-of-buffer)
      (newline))
    (write-file "/tmp/timeline.org")
    (org-agenda arg "L")))

(define-key org-mode-map (kbd "C-c t") 'org-agenda-timeline-all)

#+END_SRC

What I am doing is simply iterating through the variable org-agenda-files, which has a list of all org files to consider and, after that, making my timeline with all TODO's.
To insert an org file into the list (variable), you can use the command org-agenda-file-to-front ( or C-c [ ). This command will insert the file in your current buffer into the list of org agenda files.
To remove the file, simply use the command org-remove-file ( or C-c ] ).

After my function is made, I assigned it to the shortcut C-c t.

** magit

#+BEGIN_SRC emacs-lisp

(use-package magit
  :ensure t)

#+END_SRC

** dracula-theme

#+BEGIN_SRC emacs-lisp

(use-package dracula-theme
  :init (load-theme 'dracula t)
  :ensure t)

#+END_SRC

** relative-line-numbers

#+BEGIN_SRC emacs-lisp

(use-package relative-line-numbers
  :config (global-relative-line-numbers-mode)
  :ensure t)

#+END_SRC
* Comment/Uncomment Region Keys

#+BEGIN_SRC emacs-lisp

(global-set-key (kbd "C-a") #'comment-region)
(global-set-key (kbd "C-b") #'uncomment-region)

#+END_SRC
